[build]
  publish = "public"
  command = "echo 'No specific build command for static HTML+JS. Functions will be built by Netlify.'"

[functions]
  directory = ".netlify/functions"
  # You might not need a specific bundler if your function is simple Python.
  # Netlify will use default Python runtime.
  # node_bundler = "esbuild" # Uncomment and change if using Node.js functions